services:
  - type: web
    name: set-private
    runtime: python
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run gunicorn --worker-class gthread --workers 1 --threads 100 --bind 0.0.0.0:$PORT 'set_game.app:create_app()'
    healthCheckPath: /healthz
    envVars:
      - key: SET_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SET_TRUSTED_HOSTS
        value: set-private.onrender.com
